language: node_js

node_js: 'lts/*'

cache: yarn

script:
  - yarn lint
  - yarn unit
  - yarn build

before_deploy:
  - firebase login --reauth

deploy:
  provider: surge
  project: './dist'
  on: master
