language: node_js

node_js: 'lts/*'

cache: yarn

before_install:
  - yarn global add firebase-tools

script:
  - yarn lint
  - yarn unit
  - yarn build

before_deploy:
  - firebase login --reauth

deploy:
  provider: firebase
  token:
    secure: '$FIREBASE_TOKEN'
  project: 'grocery-store-app'
