language: node_js

node_js: 'lts/*'

cache: yarn

before_script:
  - node build/dev-server.js &  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc

script:
  - yarn lint
  - yarn unit
  - xvfb-run yarn e2e:ci
  - yarn build

deploy:
  provider: surge
  project: ./dist/
  domain: glistapp.surge.sh
  skip_cleanup: true
  on: master
