language: node_js

node_js: 'lts/*'

cache: yarn

before_script:
  - yarn global add firebase-tools

script:
  - yarn lint
  - yarn unit
  - yarn build

deploy:
  provider: firebase
  token:
    secure: "YOUR ENCRYPTED token"
